const racerNamePrefixes = [
	"The",
	"Inert",
	"Toe",
	"Finger",
	"Fond",
	"Angel Of",
	"Undulating",
	"Old Fashioned",
	"Dense",
	"Gaping",
	"Rough",
	"Uneven",
	"Even",
	"Odd",
	"Amorous",
	"Rehash The",
	"Favored",
	"As If",
	"Umm...",
	"Hmm,",
	"Cliche",
	"Blind",
	"Catatonic",
	"Who's The",
	"Where's The",
	"When's The",
	"What's The",
	"Why Not",
	"Why",
	"Chain",
	"Disinterested",
	"Fanatical",
	"Motor",
	"Verified",
	"Sanctioned",
	"Responsible",
	"Irresponsible",
	"Satirical",
	"Obligatory",
	"Questionable",
	"Debateable",
	"Suspicious",
	"Controversial",
	"Dubitable",
	"Equivocal",
	"Iffy",
	"Arguable",
	"Exceptionable",
	"Borderline",
	"Complex",
	"Unclear",
	"Inconclusive",
	"Supposed",
	"Conjected",
	"Obsolete",
	"Indicted",
	"Citing",
	"Indicting",
	"Denouncing",
	"Asserted",
	"Asserting",
	"Attested",
	"Avowed",
	"Declared",
	"Declaration Of",
	"Declaring",
	"Affirmed",
	"Affirming",
	"Abject",
	"Adorable",
	"Arch",
	"Arrrgh!",
	"Oh No,",
	"Window To The",
	"Door To The",
	"Entrance To The",
	"Widowed",
	"Minimalist",
	"Reluctant",
	"Reticent",
	"00" + Math.floor(Math.random()*9) + ": Licensed To",
	Math.floor(1 + Math.random()*111) + "%",
	Math.floor(1 + Math.random()*12) + "O'Clock",
	Math.floor(Math.random()*1000) + "mL Of",
	Math.floor(Math.random()*1000) + "Kg Of",
	Math.floor(Math.random()*1000) + "Km Of", 
	Math.floor(Math.random()*99) + " Units Of",
];

const racerNameSuffixes = [
	"V" + Math.floor(Math.random()*10) + "." + Math.floor(Math.random()*10),
	"'" + Math.floor(10 + Math.random()*89),
	Math.floor(1 + Math.random()*9) + "000",
	"Bath",
	"Authority",
	"Prominence",
	"Promenade",
	"Alley",
	"Minimalism",
	"Widow",
	"Avenger",
	"Screw",
	"Repairs",
	"Avowal",
	"Predication",
	"Profession",
	"Pronouncement",
	"Asseveration",
	"Averment",
	"Accusation",
	"Recrimination",
	"Cocktail",
	"Tornado",
	"Shrimp",
	"Ankles",
	"Cliche",
	"Punchline",
	"Favorite",
	"Litigation",
	"Lawsuit",
	"Density",
	"Propensity",
	"Tendency",
	"Etymology",
	"Politics",
	"Tautology",
	"- ology",
	"Pupil",
	"Iris",
	"Doctrine",
	"Adherents",
	"Philosopher",
	"Disciple",
	"Discipline",
	"Discharge",
  "Brush",
  "Comb",
  "Pore",
  "Follicles",
  "Chemistry",
  "Dimension",
  "Tragedy",
  "Task",
  "Beam",
  "Deception",
  "Enough",
  "Flattery",
  "Execution",
  "Executive",
  "Signals",
  "Publicity",
  "Gash",
  "Defiance",
  "Rot",
  "Diva",
];